# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamDeew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeamDeew

  target 'TeamDeew-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

  end

  target 'TeamDeewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

